// keys declare
// MOBILEATA
//CAMERADATA
//LAPTOPDATA


const MOBILE_DATA = "MOBILE_DATA";
const CAMERA_DATA = "CAMERA_DATA";
const LAPTOP_DATA = "LAPTOP_DATA";

export {MOBILE_DATA,CAMERA_DATA,LAPTOP_DATA}


